export const GROK_45_PROMPT = 'You are Amp. Help the user complete software engineering tasks.'

export const GROK_45_TOOL_NAMES = [
	'apply_patch',
	'create_file',
	'create_thread',
	'edit_file',
	'find_thread',
	'finder',
	'get_thread_status',
	'librarian',
	'oracle',
	'painter',
	'Read',
	'read_mcp_resource',
	'read_thread',
	'read_web_page',
	'send_thread_message',
	'shell_command',
	'shell_command_status',
	'skill',
	'Task',
	'update_thread',
	'view_media',
	'wait_for_threads',
	'download_thread_file',
	'download_thread_changes',
	'upload_thread_file',
	'web_search',
	'mcp__*',
	'plugin__*',
] as const
